INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Adams', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Adamsville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Afton', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Alamo', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Alcoa', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Alexandria', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Algood', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Allardt', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Allons', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Allred', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Alpine', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Altamont', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Andersonville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Antioch', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Apison', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ardmore', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Arlington', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Arnold AFB', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Arrington', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Arthur', '2022-05-31')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ashland City', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Athens', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Atoka', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Atwood', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Auburntown', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Baileyton', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bakwell', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Baneberry', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Banner Hill', '2022-05-31')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bartlett', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bath Springs', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Baxter', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bean Station', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Beech Bluff', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Beechgrove', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Beersheba Springs', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Belfast', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Belinda City', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bell Buckle', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Belle Meade', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bells', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Belvidere', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Benton', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Berry Hill', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bethel Springs', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bethpage', '2022-05-10') 
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Big Rock', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Big Sandy', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Birchwood', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Blaine', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bloomingdale', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bloomington Springs', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Blountville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bluff City', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bogota', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bolivar', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bon Aqua', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bon Aqua Junction', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bowman', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Braden', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bradford', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bradyville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bransford', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Brentwood', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Briceville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Brighton', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bristol', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Brownsville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Browsville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bruceton', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Brunswick', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Brush Creek', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Buchanan', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Buena Vista', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Buffalo Valley', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bulls Gap', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bumpus Mills', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Burlison', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Burns', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Butler', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Bybee', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Byrdstown', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Calhoun', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Camden', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Campaign', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Carthage', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Caryville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Castalian Springs', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cedar Grove', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cedar Hill', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Celina', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Centertown', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Centerville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Central', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Chapel Hill', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Chapmansboro', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Charleston', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Charlotte', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Chattanooga', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Chesterfield', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Chestnut Mound', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Chewalla', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Christiana', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Chuckey', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Church Hill', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Clairfield', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Clarkrange', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Clarksburg', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Clarksville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cleveland', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Clifton', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Clinton', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Coalfield', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Coalmont', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Coker Creek', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('College Grove', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Collegedale', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Collierville' ,'2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Collinwood', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Colonial Heights', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Columbia', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Como', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Conasauga', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Condon', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cookeville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Coopertown', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Copperhill', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cordova', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cornersville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Corryton', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cosby', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cottage Grove', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cottontown', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Counce', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Covington', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cowan', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Crab Orchard', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Crawford', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Crockett Mills', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cross Plains', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Crossville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Crump', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Culleoka', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cumberland City', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cumberland Furnace', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cumberland Gap', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cunningham', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Cypress Inn', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dancyville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dandridge', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Darden','2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dayton','2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('De Priest Bend','2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Decatur', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Decaturville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Decherd', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Deer Lodge', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Del Rio', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Delano', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dellrose','2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Denmark', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dickson','2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dixon Springs', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dodson Branch', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dover', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dowelltown', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Doyle', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dresden', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Drummonds', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Duck River', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ducktown', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Duff', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dukedom', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dunlap', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dyer', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Dyersburg', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Eads', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Eagan', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Eagleton Village', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Eagleville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('East Brainerd', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('East Chattanooga', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('East Cleveland', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('East Ridge', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Eastview', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Eaton', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Eidson', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Elgin', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Elizabethton', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Elkton', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ellendale', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Elmwood', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Elora', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Englewood', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Enville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Erin', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Erwin', '2022-05-31')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Estill Springs', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ethridge', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Etowah', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Eva', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Evensville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Fair Garden', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Fairfield', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Fairfield Glade', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Fairmount', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Fairview',	'2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Fall Branch', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Falling Water', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Farner', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Farragut',	'2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Fayetteville',	'2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Fincastle', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Finger', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Finley', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Five Points', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Flag Pond', '2022-05-31')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Flintville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Forest Hills', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Fosterville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Fowlkes', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Frankewing', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Franklin', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Friendship', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Friendsville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Fruitvale', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Gadsden', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Gainesboro', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Gallatin', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Gallaway', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Garland', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Gates', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Gatlinburg', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Georgetown', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Germantown', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Gibson', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Gilt Edge', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Gladeville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Gleason', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Goodlettsville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Goodspring', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Gordonsville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Graball', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Grand Junction', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Grandview', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Granville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Gray', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Graysville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Great Smoky Mountains Natl Park', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Green Hill', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Greenback', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Greenbrier', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Greeneville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Greenfield', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Grimsley', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Gruetli-Laager', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Guild', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Guys', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Halls', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hampshire', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hampton', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Harriman', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Harrison', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Harrogate', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hartford', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hartsville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Heiskell', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Helenwood', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Henderson', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hendersonville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Henning', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Henry', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hermitage', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hickman', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hickory Valley', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hickory Withe', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hilham', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hillsboro', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hixson', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hohenwald', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Holladay', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hollow Rock', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hopewell', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hornbeak', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hornsby', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Humboldt', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hunter', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Huntingdon', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Huntland', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Huntsville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Huron', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hurricane Mills', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Hurtingdon', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Idlewild', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Indian Mound', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Iron City', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Jacks Creek', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Jacksboro', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Jackson', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Jamestown', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Jasper', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Jefferson City', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Jellico', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Joelton', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Johnson City', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Johnsonville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Jonesborough', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Karns', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Kelso', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Kenton', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Kimball', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Kingsport', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Kingston', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Kingston Springs', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Knoxville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Kodak', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Kyles Ford', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('La Follette', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('La Grange', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('La Vergne', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Laconia', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lafayette', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lake City', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lake Tansi', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lakeland', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lakesite', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lakewood', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lancaster', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lancing', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lascassas', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Laurel Bloomery', '2022-06-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lavinia', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lawrenceburg', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lebanon', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lenoir City', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lenox', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Leoma', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lewisburg', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lexington', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Liberty', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Limestone', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Linden', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Livingston', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lobelville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lone Mountain', '2022-05-31')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lone Oak', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lookout Mountain', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Loretto', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Loudon', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Louisville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lowland', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lupton City', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Luray', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Luttrell', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lutts', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lyles', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lynchburg', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Lynnville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Macon', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Madison', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Madisonville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Manchester', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mansfield', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Martin', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Maryville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mascot', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mason', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Maury City', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Maynardville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('McDonald', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('McEwen', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('McKenzie', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('McLemoresville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('McMinnville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Medina', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Medon', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Memphis', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mercer', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Michie', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Middle Valley', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Middleton', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Midtown', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Midway', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Milan', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Milledgeville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Millersville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Milligan College', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Millington', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Milton', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Minor Hill', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Miston', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mitchellville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mohawk', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Monroe', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Monteagle', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Monterey', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mooresburg', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Morris Chapel', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Morrison', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Morristown', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Moscow', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mosheim', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Moss', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mount Carmel', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mount Juliet', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mount Pleasant', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mountain City', '2022-06-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mountain Home', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Mulberry', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Munford', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Murfreesboro', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Nashville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('New Deal', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('New Hope', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('New Johnsonville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('New Market', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('New Tazewell', '2022-05-31')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('New Union', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Newbern', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Newcomb', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Newport', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Niota', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Nolensville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Norene', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Normandy', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Norris', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Nunnelly', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Oak Grove', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Oak Hill', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Oak Ridge', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Oakdale', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Oakfield', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Oakland', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Obion', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ocoee', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Old Fort', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Old Hickory', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Olivehill', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Oliver Springs', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Olivet', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Oneida', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Only', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ooltewah', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Orlinda', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Orme', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ozone', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pall Mall', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Palmer', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Palmersville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Palmyra', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Paris', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Park City', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Parker Crossroads', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Parrottsville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Parsons', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pegram', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pelham', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Petersburg', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Petros', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Philadelphia', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pickwick Dam', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pigeon Forge', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pikeville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pine Crest', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Piney Flats', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pinson', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pioneer', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Piperton', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pittman Center', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Plainview', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pleasant Hill', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pleasant Shade', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pleasant View', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pleasantville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pocahontas', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Portland', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Powder Springs', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Powell', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Powells Crossroads', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Primm Springs', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Prospect', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pruden', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Pulaski', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Puryear', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Quebeck', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ramer', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Readyville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Reagan', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Red Bank', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Red Boiling Springs', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Reliance', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Riceville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Rickman', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Riddleton', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ridgely', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ridgeside', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ridgetop', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ripley', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Rives', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Roan Mountain', '2022-05-31')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Robbins', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Rock Island', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Rockford', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Rockvale', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Rockwood', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Rogersville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Rossville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Rugby', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Rural Hill', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Russellville', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Rutherford', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Rutledge', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Saint Andrews', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Saint Bethlehem', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Saint Joseph', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Sale Creek', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Saltillo', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Samburg', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Santa Fe', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Sardis', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Saulsbury', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Savannah', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Scotts Hill', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Selmer', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Sequatchie', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Sevierville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Sewanee', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Seymour', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Shackle Island', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Shady Valley', '2022-05-31')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Sharon', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Sharps Chapel', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Shawanee', '2022-05-31')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Shelbyville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Sherwood', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Shiloh', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Signal Mountain', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Silerton', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Silver Point', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Slayden', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Smartt', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Smithville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Smyrna', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Sneedville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Soddy-Daisy', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Somerville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('South Carthage', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('South Cleveland', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('South Fulton', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('South Pittsburg', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Southside', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Sparta', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Speedwell', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Spencer', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Spring City', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Spring Creek', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Spring Hill', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Springfield', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Springville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Spurgeon', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Stanton', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Stantonville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Stewart', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Strawberry Plains', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Sugar Tree', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Summertown', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Summitville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Sunbright', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Surgoinsville', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Sweetwater', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Taft',	'2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Talbott', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Tallassee', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Tazewell', '2022-05-31')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Telford', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Tellico Plains', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Ten Mile', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Tennessee Ridge', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Thompsons Station', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Thorn Hill', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Three Way', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Tigrett', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Tipton', '2022-04-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Tiptonville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Toone', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Townsend', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Tracy City', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Trade', '2022-05-31')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Trenton', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Trezevant', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Tri-Cities', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Trimble', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Troy', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Tullahoma', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Turtletown', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Tusculum', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Unicoi', '2022-05-31')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Union City', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Unionville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Vanleer', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Viola', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Vonore', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Walden', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Walland', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Walling', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Walnut Grove', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Walnut Hill', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Walterhill', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Wartburg', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Wartrace', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Washburn', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Watauga', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Watertown', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Watts Bar Dam', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Waverly', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Waynesboro', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Westmoreland', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Westpoint', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Westport', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('White Bluff', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('White House', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('White Pine', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Whites Creek', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Whitesburg', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Whiteside', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Whiteville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Whitleyville', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Whitwell', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Wilder', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Wildersville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Wildwood', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Wildwood Lake', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Williamsport', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Williston', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Winchester', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Winfield', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Winona', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Woodbury', '2022-05-20')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Woodland Mills', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Woodlawn', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Wrigley', '2022-05-10')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Wynnburg', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Yorkville', '2022-04-30')
INSERT INTO FrostDate (Name, AverageFrostDate) VALUES ('Yuma', '2022-04-30')